# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergetlist', '0003_auto_20160313_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='lastpoll',
            field=models.DateTimeField(default=None, verbose_name='date last pulled'),
        ),
    ]
