# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergetlist', '0004_auto_20160313_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='broadcast',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='broadcast_end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end of broadcast'),
        ),
        migrations.AlterField(
            model_name='source',
            name='lastpoll',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date last pulled'),
        ),
    ]
